from qmllm.methods.mbq_fg.entry import mbq_entry


def lagq_entry(
    model,
    prompt_inputs,
    prompt_kwargs,
    run_lagq_process: bool,
    pseudo_quant: bool,
    scale_path: str = None,
    zero_point: bool = True,
    q_group_size: int = 128,
    w_bit: int = 4,
    a_bit: int = 8,
    wa_quant: bool = True,
    loss_mode: str = "mae",
    lagq_layer_groups: str = "0-10,11-25,26-35",
    lagq_noise_bits: int = 8,
    lagq_noise_strength: float = 1.0,
    lagq_micro_batch_size: int = 0,
    lagq_stage1_samples: int = 0,
    lagq_disable_logit_sensitivity: bool = False,
    lagq_disable_attention_token_weight: bool = False,
    lagq_stage1_metric: str = "full_logit",
    lagq_text_attn_correction: str = "exposure_baseline_ratio",
    lagq_vision_query_source: str = "both",
    lagq_query_mix_alpha: float = 0.5,
):
    # Layer-aware, attention-guided fine-grained weighting:
    # - token weighting from per-layer attention
    # - optional stage-1 logit sensitivity weights by (layer-group, modality)
    return mbq_entry(
        model=model,
        prompt_inputs=prompt_inputs,
        prompt_kwargs=prompt_kwargs,
        run_mbq_process=run_lagq_process,
        pseudo_quant=pseudo_quant,
        scale_path=scale_path,
        zero_point=zero_point,
        q_group_size=q_group_size,
        w_bit=w_bit,
        a_bit=a_bit,
        wa_quant=wa_quant,
        reweight=False,
        distort=False,
        loss_mode=loss_mode,
        finegrained=True,
        finegrained_mode="attention",
        lagq_layer_groups=lagq_layer_groups,
        lagq_noise_bits=lagq_noise_bits,
        lagq_noise_strength=lagq_noise_strength,
        lagq_micro_batch_size=lagq_micro_batch_size,
        lagq_stage1_samples=lagq_stage1_samples,
        lagq_disable_logit_sensitivity=lagq_disable_logit_sensitivity,
        lagq_disable_attention_token_weight=lagq_disable_attention_token_weight,
        lagq_stage1_metric=lagq_stage1_metric,
        lagq_text_attn_correction=lagq_text_attn_correction,
        lagq_vision_query_source=lagq_vision_query_source,
        lagq_query_mix_alpha=lagq_query_mix_alpha,
    )
